#!/bin/sh

ifconfig lo up

ifconfig eth0 up
udhcpc -i eth0 -s /etc/udhcpc/default.script -b

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mount /dev/mtdblock4 /home/
